from django.apps import apps

def get_all_customs():
  
  all_models=[]
  for models in apps.get_models():
# Generated by Django 5.0.7 on 2024-08-04 14:55
    settings_models= ['LogEntry','Permission','Group','User','ContentType','Session']
    if models.__name__ not in settings_models:
      all_models.append(models.__name__)
  
  return all_models